# Generated by Django 5.0.6 on 2024-06-14 18:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadejte své jméno', max_length=50, verbose_name='Jméno uživatele')),
                ('prijmeni', models.CharField(help_text='Zadejte své příjmení', max_length=50, verbose_name='Příjmení uživatele')),
                ('nickname', models.CharField(help_text='Zadejte svou přezdívku', max_length=50, verbose_name='Přezdívka uživatele')),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(help_text='Zadejte svůj email', max_length=254, verbose_name='Email uživatele')),
                ('datum_narozeni', models.DateField(help_text='Zadejte své datum narození', verbose_name='Datum narození')),
            ],
            options={
                'verbose_name': 'Uživatel',
                'verbose_name_plural': 'Uživatelé',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Vydavatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název vydavatele je povinný údaj'}, help_text='Zadejte název vydavatele', max_length=100, verbose_name='Název vydavatele')),
            ],
            options={
                'verbose_name': 'Vydavatel',
                'verbose_name_plural': 'Vydavatele',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Vyvojar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název vývojáře je povinný údaj'}, help_text='Zadejte název vývojáře', max_length=100, verbose_name='Název vývojáře')),
            ],
            options={
                'verbose_name': 'Vývojář',
                'verbose_name_plural': 'Vývojáří',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název žánru', max_length=20, verbose_name='Název žánru')),
            ],
            options={
                'verbose_name': 'Žánr',
                'verbose_name_plural': 'Žánry',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Hra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název vývojáře je povinný údaj'}, help_text='Zadejte název hry', max_length=100, verbose_name='Název hry')),
                ('datum_vydani', models.DateField(help_text='Zadejte datum vydání hry', verbose_name='Datum vydání')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vydavatel', models.ManyToManyField(to='knihovna.vydavatel')),
                ('vyvojar', models.ManyToManyField(to='knihovna.vyvojar')),
                ('zanry', models.ManyToManyField(to='knihovna.zanr')),
            ],
            options={
                'verbose_name': 'Hra',
                'verbose_name_plural': 'Hry',
                'ordering': ['nazev'],
            },
        ),
    ]
