# Generated by Django 5.0.6 on 2024-06-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hra',
            name='fotka',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/{% "nazev" %}/'),
        ),
    ]
