# Generated by Django 5.0.6 on 2024-06-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0005_alter_hra_fotka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hra',
            name='fotka',
            field=models.ImageField(default='static/img/default.png', upload_to='static/img'),
        ),
    ]
