# Generated by Django 5.0.6 on 2024-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0007_alter_hra_fotka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vydavatel',
            options={'ordering': ['nazev'], 'verbose_name': 'Vydavatel', 'verbose_name_plural': 'Vydavatelé'},
        ),
        migrations.AlterModelOptions(
            name='vyvojar',
            options={'ordering': ['nazev'], 'verbose_name': 'Vývojář', 'verbose_name_plural': 'Vývojáři'},
        ),
        migrations.AlterField(
            model_name='hra',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='hra',
            name='nazev',
            field=models.CharField(help_text='Zadejte název hry', max_length=100, verbose_name='Název hry'),
        ),
        migrations.AlterField(
            model_name='hra',
            name='vydavatel',
            field=models.ManyToManyField(to='knihovna.vydavatel', verbose_name='Vydavatelé'),
        ),
        migrations.AlterField(
            model_name='hra',
            name='vyvojar',
            field=models.ManyToManyField(to='knihovna.vyvojar', verbose_name='Vývojáři'),
        ),
        migrations.AlterField(
            model_name='hra',
            name='zanry',
            field=models.ManyToManyField(to='knihovna.zanr', verbose_name='Žánry'),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='email',
            field=models.EmailField(help_text='Zadejte svůj email', max_length=254, unique=True, verbose_name='Email uživatele'),
        ),
        migrations.AlterField(
            model_name='vydavatel',
            name='nazev',
            field=models.CharField(help_text='Zadejte název vydavatele', max_length=100, verbose_name='Název vydavatele'),
        ),
        migrations.AlterField(
            model_name='vyvojar',
            name='nazev',
            field=models.CharField(help_text='Zadejte název vývojáře', max_length=100, verbose_name='Název vývojáře'),
        ),
    ]
