# Generated by Django 5.0.6 on 2024-06-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0008_alter_vydavatel_options_alter_vyvojar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hra',
            name='fotka',
            field=models.ImageField(default='final_project/knihovna/static/img/default.png', upload_to='final_project/knihovna/static/img'),
        ),
    ]
