# Generated by Django 5.0.6 on 2024-06-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0009_alter_hra_fotka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hra',
            name='fotka',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
