# Generated by Django 4.2.13 on 2024-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0010_alter_hra_fotka'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzivatel',
            name='fotka',
            field=models.ImageField(default='img/users/default.png', upload_to='img/users/'),
        ),
        migrations.AlterField(
            model_name='hra',
            name='fotka',
            field=models.ImageField(default='img/games/default.png', upload_to='img/games/'),
        ),
    ]
