# Generated by Django 4.2.13 on 2024-06-15 15:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0011_uzivatel_fotka_alter_hra_fotka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzivatel',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CZ', unique=True),
        ),
    ]
